samples:
  0:        # sample index, and the slice numbers
    - 0
    - 2
    - 5
    - 8

  9:
    - 0
    - 1
    - 3
    - 7

  12:
    - 0
    - 2
    - 4
    - 12

  14:
    - 0
    - 3
    - 8
    - 13

  18:
    - 0
    - 4
    - 7
    - 11

  19:
    - 0
    - 2
    - 5
    - 10

  22:
    - 0
    - 2
    - 5
    - 9

  45:
    - 0
    - 3
    - 6
    - 12

  48:
    - 0
    - 2
    - 7
    - 12

  57:
    - 0
    - 5
    - 10
    - 14

  92:
    - 0
    - 2
    - 7
    - 11

  114:
    - 0
    - 1
    - 9
    - 13

  234:
    - 0
    - 2
    - 7
    - 10

  244:
    - 0
    - 4
    - 8
    - 11

  350:
    - 0
    - 3
    - 6
    - 10