samples:
  0:      # sample index, and the slice numbers
#    - 0
    - 5
#    - 14
#    - 24
#    - 32

  7:
#    - 6
#    - 14
    - 20
    - 28
#    - 36

  20:
#    - 5
    - 11
    - 16
#    - 25
#    - 30

  45:
#    - 5
#    - 12
#    - 19
#    - 26
    - 32

  69:
#    - 9
    - 14
#    - 21
#    - 27
#    - 33

  98:
    - 7
#    - 12
#    - 21
#    - 29
#    - 33

  111:  # more slices than usual
#    - 8
#    - 12
    - 18
#    - 25
    - 31
#    - 40

  125:
#    - 5
#    - 11
#    - 19
    - 25
#    - 30

  160:  # initially tilted with different patterns
#    - 4
#    - 8
#    - 14
#    - 21
    - 26
    - 31

  184:  # bright and white shades
#    - 6
    - 12
#    - 18
#    - 27
    - 32
#    - 38